logLevel = "DEBUG"
defaultEntryPoints = ["https","http"]
[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
    entryPoint = "https"
  [entryPoints.https]
  address = ":443"
  [entryPoints.https.tls]

[docker]
 endpoint = "unix:///var/run/docker.sock"
 domain = "test.org"
 watch = true
 exposedbydefault = false

[acme]
 email = "contact@zeodine.fr"
 domain = "test.org"
 storage = "/acme.json"
 entryPoint = "https"
 OnHostRule = true
 caServer = "https://acme-staging.api.letsencrypt.org/directory"


[acme.httpChallenge]
 entryPoint = "http"